const express = require('express')
const router = express.Router()
const users = require('./usersRoutes')
const auth = require('./authRoutes')
const masuk = require('./absenMasukRoutes')
const pulang = require('./absenPulangRoutes')
const cuti = require('./cutiRoutes')
const notifPlayer = require('./notificationPlayerRoutes')
const reimbusement = require('./reimbusementRoutes')
const document = require('./documentRoutes')

router.use('/users', users)
router.use('/login', auth)
router.use('/masuk', masuk)
router.use('/pulang', pulang)
router.use('/cuti', cuti)
router.use('/reimbusement', reimbusement)
router.use('/notification', notifPlayer)
router.use('/document', document)

module.exports = router 